In [1]:
import pandas as pd
df1 = pd.read_csv('acs2015_county_data.csv')

In [17]:
df1.tai

,CensusId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
3215,72145,Puerto Rico,Vega Baja,56858,27379,29479,96.4,3.4,0.1,0.0,...,1.2,1.3,0.3,32.0,13660,78.3,17.6,4.1,0.0,15.2
3216,72147,Puerto Rico,Vieques,9130,4585,4545,96.7,2.9,0.0,0.0,...,10.8,0.0,1.4,14.0,2860,44.5,41.6,13.6,0.3,12.2
3217,72149,Puerto Rico,Villalba,24685,12086,12599,99.7,0.0,0.0,0.0,...,3.2,0.0,3.3,26.9,6795,59.2,27.5,13.1,0.2,25.9
3218,72151,Puerto Rico,Yabucoa,36279,17648,18631,99.8,0.2,0.0,0.0,...,2.3,2.3,1.5,29.5,8083,65.1,27.6,7.3,0.0,24.3
3219,72153,Puerto Rico,Yauco,39474,19047,20427,99.5,0.5,0.0,0.0,...,1.6,0.7,3.1,24.6,8923,68.0,27.6,4.4,0.0,27.1

In [18]:
df2 = pd.read_csv('store_data.csv')
df2.Postcode.unique()

array(['AD500', nan, '3167', ..., '2194', '181', '1682'], dtype=object)

In [9]:
df2 = df2[df2.Country == 'US']
df2.head(100)

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
11964,Starbucks,3513-125945,Safeway-Anchorage #1809,Licensed,5600 Debarr Rd Ste 9,Anchorage,AK,US,995042300,907-339-0900,GMT-09:00 America/Anchorage,-149.78,61.21
11965,Starbucks,74352-84449,Safeway-Anchorage #2628,Licensed,1725 Abbott Rd,Anchorage,AK,US,995073444,907-339-2800,GMT-09:00 America/Anchorage,-149.84,61.14
11966,Starbucks,12449-152385,Safeway - Anchorage #1813,Licensed,1501 Huffman Rd,Anchorage,AK,US,995153596,907-339-1300,GMT-09:00 America/Anchorage,-149.85,61.11
11967,Starbucks,24936-233524,100th & C St - Anchorage,Company Owned,"320 W. 100th Ave, 100, Southgate Shopping Ctr ...",Anchorage,AK,US,99515,(907) 227-9631,GMT-09:00 America/Anchorage,-149.89,61.13
11968,Starbucks,8973-85630,Old Seward & Diamond,Company Owned,1005 E Dimond Blvd,Anchorage,AK,US,995152050,907-344-4160,GMT-09:00 America/Anchorage,-149.86,61.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
12059,Starbucks,12493-152666,Kroger - Huntsville #677,Licensed,7090 University Dr,Huntsville,AL,US,35806,256-726-0600,GMT-06:00 America/Chicago,-86.71,34.75
12060,Starbucks,72635-32262,Super Target Huntsville ST-1346,Licensed,6275 University Dr,Huntsville,AL,US,358061776,256-922-0189,GMT-06:00 America/Chicago,-86.68,34.74
12061,Starbucks,10062-99521,Memorial Pkwy & Hwy 72,Company Owned,1015 North Memorial Pkwy,Huntsville,AL,US,358015927,256 539-3466,GMT-06:00 America/Chicago,-86.60,34.74
12062,Starbucks,11428-104120,Hwy 72 & Hughes,Company Owned,7779 Highway 72 West,Madison,AL,US,357588751,256-430-2393,GMT-06:00 America/Chicago,-86.74,34.75
12063,Starbucks,48885-260445,Kroger Madison 605,Licensed,4579 Wall Triana Hwy,Madison,AL,US,35758,256-461-0914,GMT-06:00 America/Chicago,-86.75,34.71

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3220 entries, 0 to 3219
Data columns (total 37 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CensusId         3220 non-null   int64
 1   State            3220 non-null   object
 2   County           3220 non-null   object
 3   TotalPop         3220 non-null   int64
 4   Men              3220 non-null   int64
 5   Women            3220 non-null   int64
 6   Hispanic         3220 non-null   float64
 7   White            3220 non-null   float64
 8   Black            3220 non-null   float64
 9   Native           3220 non-null   float64
 10  Asian            3220 non-null   float64
 11  Pacific          3220 non-null   float64
 12  Citizen          3220 non-null   int64
 13  Income           3219 non-null   float64
 14  IncomeErr        3219 non-null   float64
 15  IncomePerCap     3220 non-null   int64
 16  IncomePerCapErr  3220 non-null   int64
 17  Poverty          3220 non-null   float64
 18  ChildPoverty     3219 non-null   float64
 19  Professional     3220 non-null   float64
 20  Service          3220 non-null   float64
 21  Office           3220 non-null   float64
 22  Construction     3220 non-null   float64
 23  Production       3220 non-null   float64
 24  Drive            3220 non-null   float64
 25  Carpool          3220 non-null   float64
 26  Transit          3220 non-null   float64
 27  Walk             3220 non-null   float64
 28  OtherTransp      3220 non-null   float64
 29  WorkAtHome       3220 non-null   float64
 30  MeanCommute      3220 non-null   float64
 31  Employed         3220 non-null   int64
 32  PrivateWork      3220 non-null   float64
 33  PublicWork       3220 non-null   float64
 34  SelfEmployed     3220 non-null   float64
 35  FamilyWork       3220 non-null   float64
 36  Unemployment     3220 non-null   float64
dtypes: float64(27), int64(8), object(2)
memory usage: 930.9+ KB

In [12]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 13608 entries, 11964 to 25571
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Brand           13608 non-null  object
 1   Store Number    13608 non-null  object
 2   Store Name      13608 non-null  object
 3   Ownership Type  13608 non-null  object
 4   Street Address  13608 non-null  object
 5   City            13608 non-null  object
 6   State/Province  13608 non-null  object
 7   Country         13608 non-null  object
 8   Postcode        13607 non-null  object
 9   Phone Number    13122 non-null  object
 10  Timezone        13608 non-null  object
 11  Longitude       13608 non-null  float64
 12  Latitude        13608 non-null  float64
dtypes: float64(2), object(11)
memory usage: 1.5+ MB

In [15]:
df2.groupby('City').head()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
11964,Starbucks,3513-125945,Safeway-Anchorage #1809,Licensed,5600 Debarr Rd Ste 9,Anchorage,AK,US,995042300,907-339-0900,GMT-09:00 America/Anchorage,-149.78,61.21
11965,Starbucks,74352-84449,Safeway-Anchorage #2628,Licensed,1725 Abbott Rd,Anchorage,AK,US,995073444,907-339-2800,GMT-09:00 America/Anchorage,-149.84,61.14
11966,Starbucks,12449-152385,Safeway - Anchorage #1813,Licensed,1501 Huffman Rd,Anchorage,AK,US,995153596,907-339-1300,GMT-09:00 America/Anchorage,-149.85,61.11
11967,Starbucks,24936-233524,100th & C St - Anchorage,Company Owned,"320 W. 100th Ave, 100, Southgate Shopping Ctr ...",Anchorage,AK,US,99515,(907) 227-9631,GMT-09:00 America/Anchorage,-149.89,61.13
11968,Starbucks,8973-85630,Old Seward & Diamond,Company Owned,1005 E Dimond Blvd,Anchorage,AK,US,995152050,907-344-4160,GMT-09:00 America/Anchorage,-149.86,61.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25567,Starbucks,74385-87621,Safeway-Laramie #2466,Licensed,554 N 3rd St,Laramie,WY,US,820723012,307-721-5107,GMT-07:00 America/Denver,-105.59,41.32
25568,Starbucks,73320-24375,Ridley's - Laramie #1131,Licensed,3112 E. Grand,Laramie,WY,US,820705141,307-742-8146,GMT-07:00 America/Denver,-105.56,41.31
25569,Starbucks,22425-219024,Laramie - Grand & 30th,Company Owned,3021 Grand Ave,Laramie,WY,US,82070,307-742-3262,GMT-07:00 America/Denver,-105.56,41.31
25570,Starbucks,10849-103163,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,US,829015751,307-362-7145,GMT-07:00 America/Denver,-109.25,41.58
25571,Starbucks,10769-102454,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,US,828016213,307-672-5129,GMT-07:00 America/Denver,-106.94,44.77

In [16]:
df2.tail()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
25567,Starbucks,74385-87621,Safeway-Laramie #2466,Licensed,554 N 3rd St,Laramie,WY,US,820723012,307-721-5107,GMT-07:00 America/Denver,-105.59,41.32
25568,Starbucks,73320-24375,Ridley's - Laramie #1131,Licensed,3112 E. Grand,Laramie,WY,US,820705141,307-742-8146,GMT-07:00 America/Denver,-105.56,41.31
25569,Starbucks,22425-219024,Laramie - Grand & 30th,Company Owned,3021 Grand Ave,Laramie,WY,US,82070,307-742-3262,GMT-07:00 America/Denver,-105.56,41.31
25570,Starbucks,10849-103163,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,US,829015751,307-362-7145,GMT-07:00 America/Denver,-109.25,41.58
25571,Starbucks,10769-102454,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,US,828016213,307-672-5129,GMT-07:00 America/Denver,-106.94,44.77